# Tugas Kecil 1 IF3270
## Eksplorasi Library Algoritma Pembelajaran pada Jupyter Notebook
### Anggota
1. 13520101 - Aira Thalca Avila Putra
2. 13520119 - Marchotridyo

# Bagian 1: Mengenal dataset breast-cancer

In [46]:
# Load data breast_cancer
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [47]:
# Mengenal isi dari data breast_cancer
import pandas as pd
import numpy as np

def sklearn_to_df(sklearn_dataset):
    df = pd.DataFrame(sklearn_dataset.data, columns=sklearn_dataset.feature_names)
    df['target'] = pd.Series(sklearn_dataset.target)
    return df

dataset = sklearn_to_df(data)

dataset.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [48]:
# Lihat data fitur apa saja yang dimiliki oleh dataset dan nama target variabelnya
print(data.feature_names)
print(data.target_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
['malignant' 'benign']


#### Jadi, apa yang ingin dilakukan setelah melakukan pembelajaran?

Yang nantinya ingin dilakukan: Dari suatu data (yang berisikan nilai dari feature 'mean radius' s.d. 'worst fractal dimension') yang diberikan, kita ingin mengklasifikasikan data tersebut apakah bersifat 'malignant' (0) atau 'benign' (1).

#### Sebelum dimulai learning, cek beberapa informasi tambahan dahulu...

In [49]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

#### Beberapa hal yang bisa diperhatikan dari pemanggilan df.info():
1. Tidak ada missing values, dan
2. Semua tipe datanya numerik

# Bagian 2: Membagi dataset menjadi 80% data training dan 20% data testing

In [51]:
from sklearn.model_selection import train_test_split

X = data.data
Y = data.target

# Bagi menjadi 80% data training dan 20% data testing
X_train, X_test, Y_train, Y_test =  train_test_split(X, Y, test_size = 0.20)

# Bagian 3: Melakukan pembelajaran untuk membentuk classifier dengan berbagai algoritma

## Decision Tree

In [52]:
from sklearn import tree
decisionTreeClassifier = tree.DecisionTreeClassifier()
decisionTreeClassifier = decisionTreeClassifier.fit(X_train, Y_train)

# Model pohon decision tree
print(tree.export_text(decisionTreeClassifier, feature_names=list(data.feature_names)))

|--- worst area <= 884.55
|   |--- worst concave points <= 0.16
|   |   |--- worst concave points <= 0.14
|   |   |   |--- perimeter error <= 6.60
|   |   |   |   |--- area error <= 38.60
|   |   |   |   |   |--- smoothness error <= 0.00
|   |   |   |   |   |   |--- worst texture <= 27.76
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- worst texture >  27.76
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- smoothness error >  0.00
|   |   |   |   |   |   |--- worst texture <= 33.10
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- worst texture >  33.10
|   |   |   |   |   |   |   |--- worst texture <= 33.80
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- worst texture >  33.80
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- area error >  38.60
|   |   |   |   |   |--- mean symmetry <= 0.17
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- mean symmetry >  0.17
|

## ID3

In [53]:
import six
import sys
sys.modules['sklearn.externals.six'] = six

from id3 import Id3Estimator

id3Classifier = Id3Estimator()
id3Classifier = id3Classifier.fit(X_train, Y_train)

AttributeError: module 'numpy' has no attribute 'float'

## K-Means

In [23]:
from sklearn.cluster import KMeans
kMeansClassifier = KMeans(n_clusters = 2, n_init = 10)
kMeansClassifier = kMeansClassifier.fit(X_train)

## Logistic Regression

In [54]:
from sklearn.linear_model import LogisticRegression
logisticRegressionClassifier = LogisticRegression(C=100, max_iter=10000)
logisticRegressionClassifier = logisticRegressionClassifier.fit(X_train, Y_train)


## Neural Network

In [55]:
from sklearn.neural_network import MLPClassifier
mlpClassifier = MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter=1000)
mlpClassifier.fit(X_train, Y_train)

MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter=1000)

## SVM

In [56]:
from sklearn.svm import SVC

svmClassifier = SVC(C=100, kernel='linear')
svmClassifier.fit(X_train, Y_train)

SVC(C=100, kernel='linear')

# Bagian 4: Menyimpan model hasil pembelajaran

In [57]:
import pickle

pickle.dump(decisionTreeClassifier, open("decisionTreeClassifier.sav", "wb"))
pickle.dump(id3Classifier, open("id3Classifier.sav", "wb"))
pickle.dump(kMeansClassifier, open("kMeansClassifier.sav", "wb"))
pickle.dump(logisticRegressionClassifier, open("logisticRegressionClassifier.sav", "wb"))
pickle.dump(mlpClassifier, open("mlpClassifier.sav", "wb"))
pickle.dump(svmClassifier, open("svmClassifier.sav", "wb"))

# Bagian 5: Melakukan prediksi dengan loaded model

## Set up

In [59]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def predictFromModel(modelFileName):
  loadedModel = pickle.load(open(modelFileName, "rb"))
  modelName = modelFileName.rstrip(".sav")
  # Lakukan prediksi
  Y_pred = loadedModel.predict(X_test)
  accuracy = accuracy_score(Y_test, Y_pred)
  precision = precision_score(Y_test, Y_pred)
  recall = recall_score(Y_test, Y_pred)
  f1 = f1_score(Y_test, Y_pred)
  cmat = confusion_matrix(Y_test, Y_pred)
  # Output!
  print(f'''Hasil prediksi dari model {modelName}:
  
  Accuracy: {accuracy}
  Precision: {precision}
  Recall: {recall}
  F1: {f1}

  Confusion matrix:
  {cmat}
  ''')

## Decision Tree

In [60]:
predictFromModel("decisionTreeClassifier.sav")

Hasil prediksi dari model decisionTreeClassifier:
  
  Accuracy: 0.9035087719298246
  Precision: 0.9
  Recall: 0.9402985074626866
  F1: 0.9197080291970803

  Confusion matrix:
  [[40  7]
 [ 4 63]]
  


## ID3

In [61]:
predictFromModel("id3Classifier.sav")

NotFittedError: This Id3Estimator instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

## K-Means

In [63]:
predictFromModel("kMeansClassifier.sav")

Hasil prediksi dari model kMeansClassifier:
  
  Accuracy: 0.8421052631578947
  Precision: 0.788235294117647
  Recall: 1.0
  F1: 0.8815789473684211

  Confusion matrix:
  [[29 18]
 [ 0 67]]
  


## Logistic Regression

In [66]:
predictFromModel("logisticRegressionClassifier.sav")

Hasil prediksi dari model logisticRegressionClassifier:
  
  Accuracy: 0.956140350877193
  Precision: 0.9696969696969697
  Recall: 0.9552238805970149
  F1: 0.9624060150375939

  Confusion matrix:
  [[45  2]
 [ 3 64]]
  


## Neural Network

In [69]:
predictFromModel("mlpClassifier.sav")

Hasil prediksi dari model mlpClassifier:
  
  Accuracy: 0.9210526315789473
  Precision: 0.9142857142857143
  Recall: 0.9552238805970149
  F1: 0.9343065693430657

  Confusion matrix:
  [[41  6]
 [ 3 64]]
  


## SVM

In [73]:
predictFromModel("svmClassifier.sav")

Hasil prediksi dari model svmClassifier:
  
  Accuracy: 0.9298245614035088
  Precision: 0.9402985074626866
  Recall: 0.9402985074626866
  F1: 0.9402985074626865

  Confusion matrix:
  [[43  4]
 [ 4 63]]
  


# Bagian 6: Analisis hasil metrik evaluasi

Dari beberapa model yang sudah dibuat dan diuji, didapatkan hasil bahwa:
1. Skor accuracy tertinggi didapatkan oleh model ...
2. Skor precision tertinggi didapatkan oleh model ...
3. Skor recall tertinggi didapatkan oleh model ...
4. Skor F1 tertinggi didapatkan oleh model ...

Hal menarik lainnya yang ditemukan adalah karena K-Means adalah tipe learning unsupervised, skor yang didapatkan bisa rendah sekali jika ia mengklasifikan kelasnya salah (misal, yang seharusnya targetnya 0 dia klasifikasikan menjadi 1).

# Bagian 7: K-Fold Cross Validation pada DecisionTreeClassifier

In [175]:
from sklearn.model_selection import cross_validate

scores = cross_validate(decisionTreeClassifier, X, Y, cv=10, scoring=["accuracy", "f1"])
print(f"""Data 10-fold cross validation:
  Accuracy: {scores["test_accuracy"]}, with mean {np.mean(scores["test_accuracy"])}
  F1: {scores["test_f1"]}, with mean {np.mean(scores["test_f1"])}
""")

Data 10-fold cross validation:
  Accuracy: [0.92982456 0.85964912 0.9122807  0.85964912 0.92982456 0.89473684
 0.87719298 0.94736842 0.9122807  0.96428571]
  F1: [0.94117647 0.88888889 0.93150685 0.88888889 0.94594595 0.91666667
 0.90909091 0.95774648 0.92537313 0.97058824]



## Perbandingan dengan skor prediksi DecisionTreeClassifier sebelumnya

Dapat dilihat bahwa ...