# Tugas Kecil 1 IF3270
## Eksplorasi Library Algoritma Pembelajaran pada Jupyter Notebook
### Anggota
1. 13520101 - Aira Thalca Avila Putra
2. 13520119 - Marchotridyo

# Bagian 1: Mengenal dataset breast-cancer

In [156]:
# Load data breast_cancer
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [157]:
# Mengenal isi dari data breast_cancer
import pandas as pd
import numpy as np

def sklearn_to_df(sklearn_dataset):
    df = pd.DataFrame(sklearn_dataset.data, columns=sklearn_dataset.feature_names)
    df['target'] = pd.Series(sklearn_dataset.target)
    return df

dataset = sklearn_to_df(data)

dataset.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [158]:
# Lihat data fitur apa saja yang dimiliki oleh dataset dan nama target variabelnya
print(data.feature_names)
print(data.target_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
['malignant' 'benign']


#### Jadi, apa yang ingin dilakukan setelah melakukan pembelajaran?

Yang nantinya ingin dilakukan: Dari suatu data (yang berisikan nilai dari feature 'mean radius' s.d. 'worst fractal dimension') yang diberikan, kita ingin mengklasifikasikan data tersebut apakah bersifat 'malignant' (0) atau 'benign' (1).

#### Sebelum dimulai learning, cek beberapa informasi tambahan dahulu...

In [159]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

#### Beberapa hal yang bisa diperhatikan dari pemanggilan df.info():
1. Tidak ada missing values, dan
2. Semua tipe datanya numerik

# Bagian 2: Membagi dataset menjadi 80% data training dan 20% data testing

In [160]:
from sklearn.model_selection import train_test_split

X = data.data
Y = data.target

# Bagi menjadi 80% data training dan 20% data testing
X_train, X_test, Y_train, Y_test =  train_test_split(X, Y, test_size = 0.20)

# Bagian 3: Melakukan pembelajaran untuk membentuk classifier dengan berbagai algoritma

## Decision Tree

In [161]:
from sklearn import tree
decisionTreeClassifier = tree.DecisionTreeClassifier()
decisionTreeClassifier = decisionTreeClassifier.fit(X_train, Y_train)

# Model pohon decision tree
print(tree.export_text(decisionTreeClassifier, feature_names=list(data.feature_names)))

|--- worst concave points <= 0.14
|   |--- worst area <= 957.45
|   |   |--- worst texture <= 33.27
|   |   |   |--- worst concave points <= 0.14
|   |   |   |   |--- radius error <= 0.64
|   |   |   |   |   |--- smoothness error <= 0.00
|   |   |   |   |   |   |--- mean texture <= 19.74
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- mean texture >  19.74
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- smoothness error >  0.00
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- radius error >  0.64
|   |   |   |   |   |--- radius error <= 0.67
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- radius error >  0.67
|   |   |   |   |   |   |--- class: 1
|   |   |   |--- worst concave points >  0.14
|   |   |   |   |--- compactness error <= 0.03
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- compactness error >  0.03
|   |   |   |   |   |--- class: 1
|   |   |--- worst texture >  33.27
|   |   |   |--- worst perimeter <

## ID3

In [162]:
import six
import sys
sys.modules['sklearn.externals.six'] = six

from id3 import Id3Estimator

id3Classifier = Id3Estimator()
id3Classifier = id3Classifier.fit(X_train, Y_train)

## K-Means

In [163]:
from sklearn.cluster import KMeans
kMeansClassifier = KMeans(n_clusters = 2, n_init = 10)
kMeansClassifier = kMeansClassifier.fit(X_train)

## Logistic Regression

In [164]:
# @Aira

## Neural Network

In [165]:
# @Aira

## SVM

In [166]:
# @Aira

# Bagian 4: Menyimpan model hasil pembelajaran

In [167]:
import pickle

pickle.dump(decisionTreeClassifier, open("decisionTreeClassifier.sav", "wb"))
pickle.dump(id3Classifier, open("id3Classifier.sav", "wb"))
pickle.dump(kMeansClassifier, open("kMeansClassifier.sav", "wb"))
# @Aira for logistic regression, neural network, dan SVM

# Bagian 5: Melakukan prediksi dengan loaded model

## Set up

In [168]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def predictFromModel(modelFileName):
  loadedModel = pickle.load(open(modelFileName, "rb"))
  modelName = modelFileName.rstrip(".sav")
  # Lakukan prediksi
  Y_pred = loadedModel.predict(X_test)
  accuracy = accuracy_score(Y_test, Y_pred)
  precision = precision_score(Y_test, Y_pred)
  recall = recall_score(Y_test, Y_pred)
  f1 = f1_score(Y_test, Y_pred)
  cmat = confusion_matrix(Y_test, Y_pred)
  # Output!
  print(f'''Hasil prediksi dari model {modelName}:
  
  Accuracy: {accuracy}
  Precision: {precision}
  Recall: {recall}
  F1: {f1}

  Confusion matrix:
  {cmat}
  ''')

## Decision Tree

In [169]:
predictFromModel("decisionTreeClassifier.sav")

Hasil prediksi dari model decisionTreeClassifier:
  
  Accuracy: 0.9035087719298246
  Precision: 0.918918918918919
  Recall: 0.9315068493150684
  F1: 0.9251700680272108

  Confusion matrix:
  [[35  6]
 [ 5 68]]
  


## ID3

In [170]:
predictFromModel("id3Classifier.sav")

Hasil prediksi dari model id3Classifier:
  
  Accuracy: 0.9298245614035088
  Precision: 0.9452054794520548
  Recall: 0.9452054794520548
  F1: 0.9452054794520548

  Confusion matrix:
  [[37  4]
 [ 4 69]]
  


## K-Means

In [171]:
predictFromModel("kMeansClassifier.sav")

Hasil prediksi dari model kMeansClassifier:
  
  Accuracy: 0.8771929824561403
  Precision: 0.8390804597701149
  Recall: 1.0
  F1: 0.9125

  Confusion matrix:
  [[27 14]
 [ 0 73]]
  


## Logistic Regression

In [ ]:
# @Aira

## Neural Network

In [ ]:
# @Aira

## SVM

In [ ]:
# @Aira

# Bagian 6: Analisis hasil metrik evaluasi

Dari beberapa model yang sudah dibuat dan diuji, didapatkan hasil bahwa:
1. Skor accuracy tertinggi didapatkan oleh model ...
2. Skor precision tertinggi didapatkan oleh model ...
3. Skor recall tertinggi didapatkan oleh model ...
4. Skor F1 tertinggi didapatkan oleh model ...

Hal menarik lainnya yang ditemukan adalah karena K-Means adalah tipe learning unsupervised, skor yang didapatkan bisa rendah sekali jika ia mengklasifikan kelasnya salah (misal, yang seharusnya targetnya 0 dia klasifikasikan menjadi 1).

# Bagian 7: K-Fold Cross Validation pada DecisionTreeClassifier

In [175]:
from sklearn.model_selection import cross_validate

scores = cross_validate(decisionTreeClassifier, X, Y, cv=10, scoring=["accuracy", "f1"])
print(f"""Data 10-fold cross validation:
  Accuracy: {scores["test_accuracy"]}, with mean {np.mean(scores["test_accuracy"])}
  F1: {scores["test_f1"]}, with mean {np.mean(scores["test_f1"])}
""")

Data 10-fold cross validation:
  Accuracy: [0.92982456 0.85964912 0.9122807  0.85964912 0.92982456 0.89473684
 0.87719298 0.94736842 0.9122807  0.96428571]
  F1: [0.94117647 0.88888889 0.93150685 0.88888889 0.94594595 0.91666667
 0.90909091 0.95774648 0.92537313 0.97058824]

