# Tugas Kecil 1 IF3270
## Eksplorasi Library Algoritma Pembelajaran pada Jupyter Notebook
### Anggota
1. 13520101 - Aira Thalca Avila Putra
2. 13520119 - Marchotridyo

# Bagian 1: Mengenal dataset breast-cancer

In [21]:
# Load data breast_cancer
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [22]:
# Mengenal isi dari data breast_cancer
import pandas as pd
import numpy as np

def sklearn_to_df(sklearn_dataset):
    df = pd.DataFrame(sklearn_dataset.data, columns=sklearn_dataset.feature_names)
    df['target'] = pd.Series(sklearn_dataset.target)
    return df

dataset = sklearn_to_df(data)

dataset.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [23]:
# Lihat data fitur apa saja yang dimiliki oleh dataset dan nama target variabelnya
print(data.feature_names)
print(data.target_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
['malignant' 'benign']


#### Jadi, apa yang ingin dilakukan setelah melakukan pembelajaran?

Yang nantinya ingin dilakukan: Dari suatu data (yang berisikan nilai dari feature 'mean radius' s.d. 'worst fractal dimension') yang diberikan, kita ingin mengklasifikasikan data tersebut apakah bersifat 'malignant' (0) atau 'benign' (1).

#### Sebelum dimulai learning, cek beberapa informasi tambahan dahulu...

In [24]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

#### Beberapa hal yang bisa diperhatikan dari pemanggilan df.info():
1. Tidak ada missing values, dan
2. Semua tipe datanya numerik

# Bagian 2: Membagi dataset menjadi 80% data training dan 20% data testing

In [25]:
from sklearn.model_selection import train_test_split

X = data.data
Y = data.target

# Bagi menjadi 80% data training dan 20% data testing
X_train, X_test, Y_train, Y_test =  train_test_split(X, Y, test_size = 0.20)

# Bagian 3: Melakukan pembelajaran untuk membentuk classifier dengan berbagai algoritma

## Decision Tree

In [26]:
from sklearn import tree
decisionTreeClassifier = tree.DecisionTreeClassifier()
decisionTreeClassifier = decisionTreeClassifier.fit(X_train, Y_train)

# Model pohon decision tree
print(tree.export_text(decisionTreeClassifier, feature_names=list(data.feature_names)))

|--- worst perimeter <= 113.60
|   |--- worst concave points <= 0.16
|   |   |--- worst concave points <= 0.14
|   |   |   |--- area error <= 38.60
|   |   |   |   |--- smoothness error <= 0.00
|   |   |   |   |   |--- mean texture <= 19.90
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- mean texture >  19.90
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- smoothness error >  0.00
|   |   |   |   |   |--- worst texture <= 33.27
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- worst texture >  33.27
|   |   |   |   |   |   |--- worst texture <= 33.56
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- worst texture >  33.56
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |--- area error >  38.60
|   |   |   |   |--- symmetry error <= 0.02
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- symmetry error >  0.02
|   |   |   |   |   |--- worst concave points <= 0.12
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |

## ID3

In [27]:
import six
import sys
sys.modules['sklearn.externals.six'] = six

from id3 import Id3Estimator

id3Classifier = Id3Estimator()
id3Classifier = id3Classifier.fit(X_train, Y_train)

## K-Means

In [28]:
from sklearn.cluster import KMeans
kMeansClassifier = KMeans(n_clusters = 2, n_init = 10)
kMeansClassifier = kMeansClassifier.fit(X_train)

## Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression
logisticRegressionClassifier = LogisticRegression(C=100, max_iter=10000)
logisticRegressionClassifier = logisticRegressionClassifier.fit(X_train, Y_train)


## Neural Network

In [30]:
from sklearn.neural_network import MLPClassifier
mlpClassifier = MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter=1000)
mlpClassifier.fit(X_train, Y_train)

MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter=1000)

## SVM

In [31]:
from sklearn.svm import SVC

svmClassifier = SVC(C=100, kernel='linear')
svmClassifier.fit(X_train, Y_train)

SVC(C=100, kernel='linear')

# Bagian 4: Menyimpan model hasil pembelajaran

In [32]:
import pickle

pickle.dump(decisionTreeClassifier, open("decisionTreeClassifier.sav", "wb"))
pickle.dump(id3Classifier, open("id3Classifier.sav", "wb"))
pickle.dump(kMeansClassifier, open("kMeansClassifier.sav", "wb"))
pickle.dump(logisticRegressionClassifier, open("logisticRegressionClassifier.sav", "wb"))
pickle.dump(mlpClassifier, open("mlpClassifier.sav", "wb"))
pickle.dump(svmClassifier, open("svmClassifier.sav", "wb"))

# Bagian 5: Melakukan prediksi dengan loaded model

## Set up

In [33]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def predictFromModel(modelFileName):
  loadedModel = pickle.load(open(modelFileName, "rb"))
  modelName = modelFileName.rstrip(".sav")
  # Lakukan prediksi
  Y_pred = loadedModel.predict(X_test)
  accuracy = accuracy_score(Y_test, Y_pred)
  precision = precision_score(Y_test, Y_pred)
  recall = recall_score(Y_test, Y_pred)
  f1 = f1_score(Y_test, Y_pred)
  cmat = confusion_matrix(Y_test, Y_pred)
  # Output!
  print(f'''Hasil prediksi dari model {modelName}:
  
  Accuracy: {accuracy}
  Precision: {precision}
  Recall: {recall}
  F1: {f1}

  Confusion matrix:
  {cmat}
  ''')

## Decision Tree

In [34]:
predictFromModel("decisionTreeClassifier.sav")

Hasil prediksi dari model decisionTreeClassifier:
  
  Accuracy: 0.9122807017543859
  Precision: 0.9041095890410958
  Recall: 0.9565217391304348
  F1: 0.9295774647887325

  Confusion matrix:
  [[38  7]
 [ 3 66]]
  


## ID3

In [35]:
predictFromModel("id3Classifier.sav")

Hasil prediksi dari model id3Classifier:
  
  Accuracy: 0.9298245614035088
  Precision: 0.9420289855072463
  Recall: 0.9420289855072463
  F1: 0.9420289855072463

  Confusion matrix:
  [[41  4]
 [ 4 65]]
  


## K-Means

In [36]:
predictFromModel("kMeansClassifier.sav")

Hasil prediksi dari model kMeansClassifier:
  
  Accuracy: 0.8508771929824561
  Precision: 0.8023255813953488
  Recall: 1.0
  F1: 0.8903225806451612

  Confusion matrix:
  [[28 17]
 [ 0 69]]
  


## Logistic Regression

In [37]:
predictFromModel("logisticRegressionClassifier.sav")

Hasil prediksi dari model logisticRegressionClassifier:
  
  Accuracy: 0.9736842105263158
  Precision: 0.9583333333333334
  Recall: 1.0
  F1: 0.9787234042553191

  Confusion matrix:
  [[42  3]
 [ 0 69]]
  


## Neural Network

In [38]:
predictFromModel("mlpClassifier.sav")

Hasil prediksi dari model mlpClassifier:
  
  Accuracy: 0.9035087719298246
  Precision: 0.9027777777777778
  Recall: 0.9420289855072463
  F1: 0.9219858156028369

  Confusion matrix:
  [[38  7]
 [ 4 65]]
  


## SVM

In [39]:
predictFromModel("svmClassifier.sav")

Hasil prediksi dari model svmClassifier:
  
  Accuracy: 0.9649122807017544
  Precision: 0.9710144927536232
  Recall: 0.9710144927536232
  F1: 0.9710144927536232

  Confusion matrix:
  [[43  2]
 [ 2 67]]
  


# Bagian 6: Analisis hasil metrik evaluasi

Dari beberapa model yang sudah dibuat dan diuji, didapatkan hasil bahwa:
1. Skor accuracy tertinggi didapatkan oleh model Logistic Regression
2. Skor precision tertinggi didapatkan oleh model SVM
3. Skor recall tertinggi didapatkan oleh model K-Means
4. Skor F1 tertinggi didapatkan oleh model Logistic Regression

Secara umum, seluruh model yang dibuat memiliki skor yang cukup baik. Namun, ada beberapa hal yang perlu diperhatikan:
- Skor accuracy yang didapatkan oleh model K-Means adalah satu-satunya yang memiliki skor dibawah 0.9. Hal ini bisa disebabkan karena model K-Means memiliki skor yang rendah jika ia mengklasifikasikan kelasnya salah (misal, yang seharusnya targetnya 0 dia klasifikasikan menjadi 1).
- Model paling cocok yang digunakan adalah model Logistic Regression, karena memiliki skor yang paling tinggi di semua metrik evaluasi. Hal ini bisa disebabkan karena model Logistic Regression cocok digunakan untuk klasifikasi biner (mengklasifikasikan suatu data menjadi dua kelas, yaitu 0 dan 1). Tipe data yang digunakan juga cocok digunakan untuk model Logistic Regression, yaitu data numerik.
- Model SVM dengan kernel linear dan Decision Tree juga cocok untuk digunakan sebagai model karena keduanya cocok digunakan untuk klasifikasi biner. Selain itu, model SVM cocok digunakan untuk data yang memiliki banyak feature.

# Bagian 7: K-Fold Cross Validation pada DecisionTreeClassifier

In [40]:
from sklearn.model_selection import cross_validate

scores = cross_validate(decisionTreeClassifier, X, Y, cv=10, scoring=["accuracy", "f1"])
print(f"""Data 10-fold cross validation:
  Accuracy: {scores["test_accuracy"]}, with mean {np.mean(scores["test_accuracy"])}
  F1: {scores["test_f1"]}, with mean {np.mean(scores["test_f1"])}
""")

print('Average accuracy: ', scores['test_accuracy'].mean())
print('Average f1: ', scores['test_f1'].mean())

Data 10-fold cross validation:
  Accuracy: [0.92982456 0.9122807  0.92982456 0.9122807  0.94736842 0.89473684
 0.87719298 0.94736842 0.92982456 0.89285714], with mean 0.9173558897243106
  F1: [0.94117647 0.92957746 0.94594595 0.93150685 0.95774648 0.91666667
 0.90410959 0.95774648 0.94117647 0.91176471], with mean 0.9337417120562812

Average accuracy:  0.9173558897243106
Average f1:  0.9337417120562812


## Perbandingan dengan skor prediksi DecisionTreeClassifier sebelumnya

Dapat dilihat bahwa menurut akurasi antara K-Fold Cross Validation dan prediksi DecisionTreeClassifier sebelumnya, kedua skor tersebut hampir sama. Hal ini bisa disebabkan karena jumlah data yang digunakan untuk melakukan K-Fold Cross Validation adalah 80% dari data yang ada, sehingga jumlah data yang digunakan untuk melakukan K-Fold Cross Validation hampir sama dengan jumlah data yang digunakan untuk melakukan prediksi DecisionTreeClassifier sebelumnya. Dalam beberapa percobaa, nilai akurasi yang didapatkan dari K-Fold Cross Validation kadang lebih baik dan kadang lebih buruk dari prediksi DecisionTreeClassifier sebelumnya. Secara keseluruhan, K-Fold Cross Validation memberikan gambaran yang baik mengenai performa model, dalam hal ini DecisionTreeClassifier.